name: Run Unit Tests
on:
  workflow_dispatch:

jobs:
  build_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.10
      - name: Install Build Tools
        run: |
          python -m pip install build wheel
      - name: Build Distribution Packages
        run: |
          python setup.py bdist_wheel
  unit_tests:
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10, 3.11]
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{secrets.DL_API_KEY}}
    steps:
      - uses: actions/checkout@v2
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements.txt
          pip install -r requirements/test_requirements.txt
      - name: Test Language Detector
        run: |
          pytest tests/unittests/lang_detect_tests.py --doctest-modules --junitxml=tests/lang-detect-test-results.xml
      - name: Upload language detector test results
        uses: actions/upload-artifact@v2
        with:
          name: lang-detect-test-results
          path: tests/lang-detect-test-results.xml
      - name: Test Language Translator
        run: |
          pytest tests/unittests/lang_translate_tests.py --doctest-modules --junitxml=tests/lang-translate-test-results.xml
      - name: Upload language translator test results
        uses: actions/upload-artifact@v2
        with:
          name: lang-translate-test-results
          path: tests/lang-translate-test-results.xml
